### ISSUE TITLE
Describe commands for running Packit CI

### ISSUE THREAD

**Issue by spetrosi** [linux-system-roles/keylime_server#6]
In https://github.com/linux-system-roles/keylime_server/blob/main/contributing.md, let's describe how to control Packit CI, i.e. what comments to leave on PRs to run and re-run the tests. I know there is `/packit test` to rerun all tests, maybe there are some more commands e.g. to run only failing tests. @kkaarreell are there any more comments?

**Comment by spetrosi** [comment]
Okay, we can mention it just in case, an also maybe provide some context about Packit and how the tests are done

**Comment by kkaarreell** [comment]
There is also very good documentation, once can start e.g. with https://packit.dev/docs/testing-farm/.
